### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by yanzhuang-h** [yanzhuang-h/get_douban_top250_movies#1]
help me to develop my code better!

**Comment by CoDINGGOD756w98** [comment]
can you help me

**Comment by yanzhuang-h** [comment]
?what do you mean

**Comment by CoDINGGOD756w98** [comment]
im new and im tying to code a rock paper scissors game and its not working

**Comment by yanzhuang-h** [comment]
so how can help u

**Comment by CoDINGGOD756w98** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
		content="width=device-width,
				initial-scale=1.0">
	<link rel="stylesheet" href="styles.css">
	<title>Rock Paper Scissor</title>
</head>
<body>
	<section class="game">
		
		<div class="title">Rock Paper Scissor</div>
		
		
		<div class="score">
			<div class="playerScore">
				<h2>Player</h2>
				<p class="p-count count">0</p>

			</div>	
			<div class="computerScore">
				<h2>Computer</h2>
				<p class="c-count count">0</p>

			</div>
		</div>
		
		<div class="move">Choose your move</div>
		
		
		<div class="movesleft">Moves Left: 10 </div>
		
		
		<div class="options">
			<button class="rock">Rock</button>
			<button class="paper">Paper</button>
			<button class="scissor">Scissors</button>	
		</div>
		
		
 		<div class="result"></div>
		
		
		<button class="reload"></button>

	</section>

	<script src="app.js"></script>
</body>
</html>

**Comment by CoDINGGOD756w98** [comment]
/* styles.css */
/* universal selector - Applies to whole document */
*{
	padding: 0;
	margin: 0;
	box-sizing: border-box;
	background: #082c6c;
	color: #fff;
}
/* To center everything in game */
.game{
	display: flex;
	flex-direction: column;
	height: 100vh;
	width: 100vw;
	justify-content: center;
	align-items: center;
}

/* Title of the game */
.title{
	position: absolute;
	top: 0;
	font-size: 4rem;
	z-index: 2;
}

/* Score Board */
.score{
	display: flex;
	width: 30vw;
	justify-content: space-evenly;
	position: absolute;
	top: 70px;
	z-index: 1;
}

/* Score */
.p-count,.c-count{
	text-align: center;
	font-size: 1.5rem;
	margin-top: 1rem;
}

/* displaying three buttons in one line */
.options{
	display: flex;
	width: 50vw;
	justify-content: space-evenly;
	margin-top: 2rem;
}

/* Styling on all three buttons */
.rock, .paper, .scissor{
	padding: 0.8rem;
	width: 100px;
	border-radius: 10px;
	background: green;
	outline: none;
	border-color: green;
	border: none;
	cursor: pointer;
}

.move{
	font-size: 2rem;
	font-weight: bold;
}

/* Reload button style */
.reload {
	display: none;
	margin-top: 2rem;
	padding: 1rem;
	background: green;
	outline: none;
	border: none;
	border-radius: 10px;
	cursor: pointer;
}

.result{
	margin-top: 20px;
	font-size: 1.2rem;
}

/* Responsive Design */
@media screen and (max-width: 612px)
{
	.title{
		text-align: center;
	}
	.score{
		position: absolute;
		top: 200px;
		width: 100vw;
	}
	.options{
		width: 100vw;
	}

**Comment by CoDINGGOD756w98** [comment]
/* styles.css */
/* universal selector - Applies to whole document */
*{
	padding: 0;
	margin: 0;
	box-sizing: border-box;
	background: #082c6c;
	color: #fff;
}
/* To center everything in game */
.game{
	display: flex;
	flex-direction: column;
	height: 100vh;
	width: 100vw;
	justify-content: center;
	align-items: center;
}

/* Title of the game */
.title{
	position: absolute;
	top: 0;
	font-size: 4rem;
	z-index: 2;
}

/* Score Board */
.score{
	display: flex;
	width: 30vw;
	justify-content: space-evenly;
	position: absolute;
	top: 70px;
	z-index: 1;
}

/* Score */
.p-count,.c-count{
	text-align: center;
	font-size: 1.5rem;
	margin-top: 1rem;
}

/* displaying three buttons in one line */
.options{
	display: flex;
	width: 50vw;
	justify-content: space-evenly;
	margin-top: 2rem;
}

/* Styling on all three buttons */
.rock, .paper, .scissor{
	padding: 0.8rem;
	width: 100px;
	border-radius: 10px;
	background: green;
	outline: none;
	border-color: green;
	border: none;
	cursor: pointer;
}

.move{
	font-size: 2rem;
	font-weight: bold;
}

/* Reload button style */
.reload {
	display: none;
	margin-top: 2rem;
	padding: 1rem;
	background: green;
	outline: none;
	border: none;
	border-radius: 10px;
	cursor: pointer;
}

.result{
	margin-top: 20px;
	font-size: 1.2rem;
}

/* Responsive Design */
@media screen and (max-width: 612px)
{
	.title{
		text-align: center;
	}
	.score{
		position: absolute;
		top: 200px;
		width: 100vw;
	}
	.options{
		width: 100vw;
	}

**Comment by CoDINGGOD756w98** [comment]
i put this in and i cant figure out whats wrong could you try to fix it

**Comment by CoDINGGOD756w98** [comment]
please

**Comment by yanzhuang-h** [comment]
my pleasure,i will try my best to help u

**Comment by yanzhuang-h** [comment]
the js codes?

**Comment by CoDINGGOD756w98** [comment]
Yes

**Comment by CoDINGGOD756w98** [comment]
Its the JS or the HTML

**Comment by yanzhuang-h** [comment]
are you chinese

**Comment by CoDINGGOD756w98** [comment]
no

**Comment by yanzhuang-h** [comment]
so what nationality are you from?

**Comment by CoDINGGOD756w98** [comment]
Canadian

**Comment by yanzhuang-h** [comment]
ok,it may take some time,and its already night here,i need to sleep

**Comment by CoDINGGOD756w98** [comment]
Thank you

**Comment by yanzhuang-h** [comment]
hey, my friend, i just finished a simple demo for your codes,it already accomplished the basic function, but it may looks a little sb, maybe i will continue to optimize it

**Comment by yanzhuang-h** [comment]
@CoDINGGOD756w98

**Comment by yanzhuang-h** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            background: #082c6c;
            color: #fff;
        }

        /* / To center everything in game */
        .game {
            display: flex;
            flex-direction: column;
            height: 100vh;
            width: 100vw;
            justify-content: center;
            align-items: center;
        }

        /* Title of the game */
        .title {
            position: absolute;
            top: 0;
            font-size: 4rem;
            z-index: 2;
        }

        /* Score Board */
        .score {
            display: flex;
            width: 30vw;
            justify-content: space-evenly;
            position: absolute;
            top: 70px;
            z-index: 1;
        }

        /* Score */
        .p-count,
        .c-count {
            text-align: center;
            font-size: 1.5rem;
            margin-top: 1rem;
        }

        /* displaying three buttons in one line */
        .options {
            display: flex;
            width: 50vw;
            justify-content: space-evenly;
            margin-top: 2rem;
        }

        /* Styling on all three buttons */
        .rock,
        .paper,
        .scissor {
            padding: 0.8rem;
            width: 100px;
            border-radius: 10px;
            background: green;
            outline: none;
            border-color: green;
            border: none;
            cursor: pointer;
        }

        .move {
            font-size: 2rem;
            font-weight: bold;
        }

        /* Reload button style */
        .reload {
            display: none;
            margin-top: 2rem;
            padding: 1rem;
            background: green;
            outline: none;
            border: none;
            border-radius: 10px;
            cursor: pointer;
        }

        .result {
            margin-top: 20px;
            font-size: 1.2rem;
        }

        /* Responsive Design */
        @media screen and (max-width: 612px) {
            .title {
                text-align: center;
            }

            .score {
                position: absolute;
                top: 200px;
                width: 100vw;
            }

            .options {
                width: 100vw;
            }
    </style>
</head>

<body>
    <section class="game">
        
        <div class="score">
            <div class="playerScore">
                <h2>Player</h2>
                <p class="p-count count">0</p>

            </div>
            <div class="computerScore">
                <h2>Computer</h2>
                <p class="c-count count">0</p>

            </div>
        </div>

        <div class="move">Choose your move</div>

        
        <div class="movesleft">Moves Left: 10 </div>

        
        <div class="options">
            <button class="rock">Rock</button>
            <button class="paper">Paper</button>
            <button class="scissor">Scissors</button>
        </div>

        
        <div class="result"></div>

        
        <button class="reload">reload</button>
    </section>


    
    <script>
        const options = document.querySelector('.options')
        const movesleft = document.querySelector('.movesleft')
        const reload = document.querySelector('.reload')
        const p_score = document.querySelector('.p-count')
        const c_score = document.querySelector('.c-count')
        let count = 10
        let p_count = 0
        let c_count = 0

        options.addEventListener('click', function (e) {
            movesleft.innerHTML = `Moves Left: ${--count} `

            //1 means rock, 2 means paper, 3 means scissor
            let computer_choice = Math.floor(Math.random() * 3 + 1)

            if (computer_choice == 1) {
                console.log('the cpmputer choose the rock')
            }
            if (computer_choice == 2) {
                console.log('the cpmputer choose the paper')
            }
            if (computer_choice == 3) {
                console.log('the cpmputer choose the scissors')
            }
            console.log(`you choose the ${e.target.innerHTML}`)

            compare(computer_choice, e.target.innerHTML)

            if (count == 0) {
                movesleft.innerHTML = `Moves Left: ${count} `
                alert('game over!')
                alert(`The computer got scores: ${c_count}\nThe player got scores: ${p_count}`)
                count = 10
                c_count = 0
                p_count = 0
                movesleft.innerHTML = `Moves Left: ${count} `
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
        })

        reload.addEventListener('click', function () {
            count = 10
            c_count = 0
            p_count = 0
            movesleft.innerHTML = `Moves Left: ${count} `
            p_score.innerHTML = `${p_count}`
            c_score.innerHTML = `${c_count}`
        })

        function compare(computer_choice, mychoice) {
            if (computer_choice == 1 && mychoice == 'Rock') {
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 1 && mychoice == 'Scissors') {
                c_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 1 && mychoice == 'Paper') {
                p_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }


            if (computer_choice == 2 && mychoice == 'Rock') {
                c_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 2 && mychoice == 'Scissors') {
                p_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 2 && mychoice == 'Paper') {
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }


            if (computer_choice == 3 && mychoice == 'Rock') {
                p_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 3 && mychoice == 'Scissors') {
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 3 && mychoice == 'Paper') {
                c_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
        }
    </script>
</body>

</html>`

**Comment by yanzhuang-h** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            background: #082c6c;
            color: #fff;
        }

        /* / To center everything in game */
        .game {
            display: flex;
            flex-direction: column;
            height: 100vh;
            width: 100vw;
            justify-content: center;
            align-items: center;
        }

        /* Title of the game */
        .title {
            position: absolute;
            top: 0;
            font-size: 4rem;
            z-index: 2;
        }

        /* Score Board */
        .score {
            display: flex;
            width: 30vw;
            justify-content: space-evenly;
            position: absolute;
            top: 70px;
            z-index: 1;
        }

        /* Score */
        .p-count,
        .c-count {
            text-align: center;
            font-size: 1.5rem;
            margin-top: 1rem;
        }

        /* displaying three buttons in one line */
        .options {
            display: flex;
            width: 50vw;
            justify-content: space-evenly;
            margin-top: 2rem;
        }

        /* Styling on all three buttons */
        .rock,
        .paper,
        .scissor {
            padding: 0.8rem;
            width: 100px;
            border-radius: 10px;
            background: green;
            outline: none;
            border-color: green;
            border: none;
            cursor: pointer;
        }

        .move {
            font-size: 2rem;
            font-weight: bold;
        }

        /* Reload button style */
        .reload {
            display: none;
            margin-top: 2rem;
            padding: 1rem;
            background: green;
            outline: none;
            border: none;
            border-radius: 10px;
            cursor: pointer;
        }

        .result {
            margin-top: 20px;
            font-size: 1.2rem;
        }

        /* Responsive Design */
        @media screen and (max-width: 612px) {
            .title {
                text-align: center;
            }

            .score {
                position: absolute;
                top: 200px;
                width: 100vw;
            }

            .options {
                width: 100vw;
            }
    </style>
</head>

<body>
    <section class="game">
        
        <div class="score">
            <div class="playerScore">
                <h2>Player</h2>
                <p class="p-count count">0</p>

            </div>
            <div class="computerScore">
                <h2>Computer</h2>
                <p class="c-count count">0</p>

            </div>
        </div>

        <div class="move">Choose your move</div>

        
        <div class="movesleft">Moves Left: 10 </div>

        
        <div class="options">
            <button class="rock">Rock</button>
            <button class="paper">Paper</button>
            <button class="scissor">Scissors</button>
        </div>

        
        <div class="result"></div>

        
        <button class="reload">reload</button>
    </section>


    
    <script>
        const options = document.querySelector('.options')
        const movesleft = document.querySelector('.movesleft')
        const reload = document.querySelector('.reload')
        const p_score = document.querySelector('.p-count')
        const c_score = document.querySelector('.c-count')
        let count = 10
        let p_count = 0
        let c_count = 0

        options.addEventListener('click', function (e) {
            movesleft.innerHTML = `Moves Left: ${--count} `

            //1 means rock, 2 means paper, 3 means scissor
            let computer_choice = Math.floor(Math.random() * 3 + 1)

            if (computer_choice == 1) {
                console.log('the cpmputer choose the rock')
            }
            if (computer_choice == 2) {
                console.log('the cpmputer choose the paper')
            }
            if (computer_choice == 3) {
                console.log('the cpmputer choose the scissors')
            }
            console.log(`you choose the ${e.target.innerHTML}`)

            compare(computer_choice, e.target.innerHTML)

            if (count == 0) {
                movesleft.innerHTML = `Moves Left: ${count} `
                alert('game over!')
                alert(`The computer got scores: ${c_count}\nThe player got scores: ${p_count}`)
                count = 10
                c_count = 0
                p_count = 0
                movesleft.innerHTML = `Moves Left: ${count} `
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
        })

        reload.addEventListener('click', function () {
            count = 10
            c_count = 0
            p_count = 0
            movesleft.innerHTML = `Moves Left: ${count} `
            p_score.innerHTML = `${p_count}`
            c_score.innerHTML = `${c_count}`
        })

        function compare(computer_choice, mychoice) {
            if (computer_choice == 1 && mychoice == 'Rock') {
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 1 && mychoice == 'Scissors') {
                c_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 1 && mychoice == 'Paper') {
                p_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }


            if (computer_choice == 2 && mychoice == 'Rock') {
                c_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 2 && mychoice == 'Scissors') {
                p_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 2 && mychoice == 'Paper') {
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }


            if (computer_choice == 3 && mychoice == 'Rock') {
                p_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 3 && mychoice == 'Scissors') {
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
            if (computer_choice == 3 && mychoice == 'Paper') {
                c_count += 1
                p_score.innerHTML = `${p_count}`
                c_score.innerHTML = `${c_count}`
            }
        }
    </script>
</body>

</html>

**Comment by yanzhuang-h** [comment]
if you still need the code ,you can leave me your email,and i will send you the code ,and we can talk about other code-question in the future

**Comment by CoDINGGOD756w98** [comment]
sounds good thank you verry much

**Comment by CoDINGGOD756w98** [comment]
thank you for helping me my email is shrekanator1234@gmail.com if you could send me the code
